from docx import Document
from docx.shared import Inches
import pyttsx3

def speak(text):
    pyttsx3.speak(text)

document = Document()

# profile picture
document.add_picture("pp.jpg", width=Inches(2), height=Inches(2))

# Personal details
Name = input("what is your name? ")
speak("Hello" + Name + "Welcome to Demo Cv python generator project")
Phone_number = input("what is your phone number? ")
Email = input("what is your email address? ")

document.add_paragraph(
    Name + " | " + Phone_number + " | " + Email)

# about me
document.add_heading("About me")
about_me = input("Tell me about yourself: ")
document.add_paragraph(about_me)

# work experience
document.add_heading("Work experience")
p = document.add_paragraph()

company = input("What is your company name? ")
from_date = input("From Date: ")
to_date = input("To Date: ")


p.add_run(company + " ").bold = True
p.add_run(from_date + " - " + to_date + '\n').italic = True

experience_description = input(
    "what's your experience at " + company + " ")
p.add_run(experience_description)

# more experiences
while True:
    has_more_experiences = input(
        "Do you have more expriences? Yes or No ").lower()
    if has_more_experiences == "yes":
        p = document.add_paragraph()

        company = input("What is your company name? ")
        from_date = input("From Date: ")
        to_date = input("To Date: ")

        p.add_run(company + " ").bold = True
        p.add_run(from_date + " - " + to_date + '\n').italic = True

        experience_description = input(
            "what's your experience at " + company + " ")
        p.add_run(experience_description)
    else:
        break

# Skill description
document.add_heading("skills")

skill = input("Enter skill ")
p = document.add_paragraph(skill)
p.style = "List Bullet"

# more skills
while True:
    has_more_skills = input(
        "Do you have any more skill? Yes or No  ").lower()
    if has_more_skills == "yes":
        skill = input("Enter skill ")
        p = document.add_paragraph(skill)
        p.style = "List Bullet"
    else:
        break

#footer
section = document.sections[0]
footer = section.footer
p = footer.paragraphs[0]
p.text = "CV generated by eneojo using python"

document.save("cv.docx")
